# Generated by Django 5.2.7 on 2025-11-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.fooditems')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'cart',
                'db_table': 'cart',
                'ordering': ['-id'],
            },
        ),
    ]
