# Generated by Django 5.2.7 on 2025-11-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
