# Generated by Django 5.2.7 on 2025-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
