# Generated by Django 5.2.7 on 2025-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_address_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_totel', models.IntegerField()),
                ('offer_price', models.IntegerField(default=0)),
                ('delivary_charge', models.IntegerField(default=0)),
                ('totel', models.IntegerField()),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'db_table': 'bill',
                'ordering': ['-id'],
            },
        ),
    ]
