# Generated by Django 5.2.7 on 2025-11-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_totel',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
