# Generated by Django 5.2.7 on 2025-11-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'food_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='store')),
                ('tagline', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('time', models.IntegerField()),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stories',
                'db_table': 'restaurent_store',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Storecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='category')),
            ],
            options={
                'verbose_name': 'store category',
                'verbose_name_plural': 'store categories',
                'db_table': 'restaurent_store_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
                'db_table': 'restaurent_slider',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='fooditem')),
                ('price', models.IntegerField()),
                ('is_veg', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.foodcatagory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store')),
            ],
            options={
                'verbose_name': 'items',
                'verbose_name_plural': 'items',
                'db_table': 'food_items',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='foodcatagory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='catagorey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurent.storecategory'),
        ),
    ]
